/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetsNewRouteImport } from './routes/budgets/new'
import { Route as BudgetsBudgetIdRouteImport } from './routes/budgets/$budgetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsNewRoute = BudgetsNewRouteImport.update({
  id: '/budgets/new',
  path: '/budgets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsBudgetIdRoute = BudgetsBudgetIdRouteImport.update({
  id: '/budgets/$budgetId',
  path: '/budgets/$budgetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRoute
  '/budgets/new': typeof BudgetsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRoute
  '/budgets/new': typeof BudgetsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRoute
  '/budgets/new': typeof BudgetsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/budgets/$budgetId' | '/budgets/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/budgets/$budgetId' | '/budgets/new'
  id: '__root__' | '/' | '/budgets/$budgetId' | '/budgets/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetsBudgetIdRoute: typeof BudgetsBudgetIdRoute
  BudgetsNewRoute: typeof BudgetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/new': {
      id: '/budgets/new'
      path: '/budgets/new'
      fullPath: '/budgets/new'
      preLoaderRoute: typeof BudgetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$budgetId': {
      id: '/budgets/$budgetId'
      path: '/budgets/$budgetId'
      fullPath: '/budgets/$budgetId'
      preLoaderRoute: typeof BudgetsBudgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetsBudgetIdRoute: BudgetsBudgetIdRoute,
  BudgetsNewRoute: BudgetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
